'use strict';
const works = window.ARTWORKS;
const $ = selector => document.querySelector(selector);
const gallery = $('#gallery'), stage = $('#stage'), track = $('#track'), panel = $('#panel');
let current = 0, entered = false, busy = false, exhibition = false, idleTimer, drag = null, order = null, lastFocus;
const reduced = matchMedia('(prefers-reduced-motion: reduce)');
const escapeHTML = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pad = n => String(n).padStart(2,'0');
function makeSlide(index) {
 const work = works[index], figure = document.createElement('figure'); figure.className = 'slide';
 const img = new Image(); img.src = work.image; img.srcset = `${work.small} 800w, ${work.image} 1800w`; img.sizes='(max-width: 600px) 95vw, 80vw'; img.alt = `${work.title} — a painting by Eric Ernstberger`; img.draggable=false;
 img.addEventListener('error',()=>{const text=document.createElement('span');text.className='image-error';text.textContent='Artwork could not load. Please refresh.';figure.append(text);},{once:true});
 figure.append(img); return figure;
}
function neighbors(){return [(current-1+works.length)%works.length,current,(current+1)%works.length];}
function rest(){track.style.transition='none';track.replaceChildren(...neighbors().map(makeSlide));track.style.transform='translateX(-100%)';[...track.children].forEach((el,i)=>el.setAttribute('aria-hidden',String(i!==1)));}
function updateInfo(){const w=works[current];$('#counter').textContent=`${pad(current+1)} / ${pad(works.length)}`;$('#art-title').textContent=w.title;$('#art-id').textContent=w.id+' · PREVIEW ID';$('#exhibition-title').textContent=w.title;$('#announcement').textContent=`${w.title}, painting ${current+1} of ${works.length}`;}
function go(direction){if(busy||panel.open||!entered)return;busy=true;$('#poem-open').disabled=true;$('#order-open').disabled=true;track.style.transition=reduced.matches?'none':'transform 440ms cubic-bezier(.65,0,.3,1)';track.style.transform=`translateX(${direction>0?-200:0}%)`;setTimeout(()=>{current=(current+direction+works.length)%works.length;rest();updateInfo();busy=false;$('#poem-open').disabled=false;$('#order-open').disabled=false;},reduced.matches?0:450);wake();}
function enter(){entered=true;gallery.hidden=false;$('#landing').inert=true;$('#landing').classList.add('departed');rest();updateInfo();$('#home').focus();}
$('#enter').onclick=enter;
$('#home').onclick=()=>{entered=false;gallery.hidden=true;$('#landing').inert=false;$('#landing').classList.remove('departed');$('#enter').focus();};
document.querySelectorAll('[data-direction]').forEach(b=>b.onclick=()=>go(Number(b.dataset.direction)));
function wake(){if(!exhibition)return;$('#exhibition-controls').classList.remove('idle');clearTimeout(idleTimer);idleTimer=setTimeout(()=>$('#exhibition-controls').classList.add('idle'),2800);}
async function setExhibition(on){exhibition=on;document.body.classList.toggle('exhibition',on);if(on){wake();$('#exit-exhibition').focus();try{if(!document.fullscreenElement&&document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();}catch{/* In-page exhibition mode remains available. */}}else{clearTimeout(idleTimer);if(document.fullscreenElement)try{await document.exitFullscreen();}catch{}$('#exhibition').focus();}}
$('#exhibition').onclick=()=>setExhibition(true);$('#exit-exhibition').onclick=()=>setExhibition(false);
document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement&&exhibition)setExhibition(false);});
document.addEventListener('pointermove',wake);document.addEventListener('pointerdown',wake);
document.addEventListener('keydown',e=>{if(panel.open||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.key==='Escape'&&exhibition){setExhibition(false);return;}if(!entered)return;if(e.key==='ArrowLeft'){e.preventDefault();go(-1);}if(e.key==='ArrowRight'||(e.code==='Space'&&e.target.tagName!=='BUTTON')){e.preventDefault();go(1);}if(e.key.toLowerCase()==='f'){e.preventDefault();setExhibition(!exhibition);}});
stage.addEventListener('pointerdown',e=>{if(busy||panel.open||e.button!==0)return;drag={id:e.pointerId,x:e.clientX,y:e.clientY,dx:0};stage.setPointerCapture(e.pointerId);track.style.transition='none';});
stage.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;drag.dx=e.clientX-drag.x;if(Math.abs(e.clientY-drag.y)>Math.abs(drag.dx)&&Math.abs(drag.dx)<15)return;track.style.transform=`translateX(calc(-100% + ${drag.dx}px))`;});
function endDrag(cancelled=false){if(!drag)return;const dx=drag.dx;drag=null;if(!cancelled&&Math.abs(dx)>Math.min(100,stage.clientWidth*.17))go(dx<0?1:-1);else{track.style.transition=reduced.matches?'none':'transform 250ms ease-out';track.style.transform='translateX(-100%)';}}
stage.addEventListener('pointerup',()=>endDrag());stage.addEventListener('pointercancel',()=>endDrag(true));
function openPanel(type){lastFocus=document.activeElement;$('#panel-kicker').textContent=type;panel.showModal();$('#panel-close').focus();}
function closePanel(){panel.close();order=null;$('#panel-content').replaceChildren();lastFocus?.focus();}
$('#panel-close').onclick=closePanel;panel.addEventListener('cancel',e=>{e.preventDefault();closePanel();});
$('#poem-open').onclick=()=>{const w=works[current];$('#panel-content').innerHTML=`<h2 id="panel-title">${escapeHTML(w.title)}</h2><p class="byline">Eric Ernstberger</p><div class="poem-copy">${escapeHTML(w.poem||'The poem for this painting will appear here.')}</div>${w.poem?'':'<p class="note">Development preview · Eric’s poem has not yet been supplied.</p>'}`;openPanel('PAINTING & POEM');};
function options(w){return ['Small','Medium','Large'].map((name,i)=>{const h=[12.1,16.5,22][i],width=h*w.width/w.height;return {name,sku:w.id+'-'+name[0],width,height:h,sheetWidth:width+6,sheetHeight:h+6};});}
const dimensions=(w,h)=>`${w.toFixed(2)} × ${h.toFixed(2)} in.`;
const selected=()=>options(works[order.art])[order.size];
$('#order-open').onclick=()=>{order={art:current,step:0,size:1,quantity:1,delivery:{}};renderOrder();openPanel('ORDER PRINT · PREVIEW');};
function renderOrder(){const w=works[order.art], names=['PRINT','DELIVERY','REVIEW','PAYMENT'];$('#panel-content').innerHTML=`<h2 id="panel-title">${escapeHTML(w.title)}</h2><p class="byline">${w.id} · Eric Ernstberger</p><ol class="steps" aria-label="Order progress">${names.map((n,i)=>`<li class="${order.step===i?'active':''}" ${order.step===i?'aria-current="step"':''}>${i+1} ${n}</li>`).join('')}</ol><div id="order-body"></div>`;
 const body=$('#order-body');
 if(order.step===0){body.innerHTML=`<div class="print-preview"><img src="${w.small}" alt="${escapeHTML(w.title)} print preview"><p>A print of the complete painting.<br>Three-inch white border on every side.</p></div><p class="note">Illustrative dimensions, pending Eric’s approval. Pricing, paper and delivery timing to be confirmed.</p><form id="print-form"><fieldset class="size-options"><legend>Select a print size</legend>${options(w).map((s,i)=>`<label class="size-option"><input type="radio" name="size" value="${i}" ${i===order.size?'checked':''}><span><strong>${s.name}</strong><small>Image ${dimensions(s.width,s.height)}<br>Sheet ${dimensions(s.sheetWidth,s.sheetHeight)}</small></span></label>`).join('')}</fieldset><label class="field">Quantity<input name="quantity" type="number" min="1" max="20" step="1" required value="${order.quantity}"></label><button class="primary">CONTINUE TO DELIVERY →</button></form>`;$('#print-form').onsubmit=e=>{e.preventDefault();const data=new FormData(e.target);order.size=Number(data.get('size'));order.quantity=Number(data.get('quantity'));order.step=1;renderOrder();};}
 if(order.step===1){const fields=[['name','Full name','text','Sample Visitor'],['email','Email address','email','visitor@example.com'],['address','Street address','text','123 Example Street'],['city','City','text','Sample City'],['region','State / province','text','IN'],['postal','Postal code','text','46000'],['country','Country','text','United States']];body.innerHTML=`<p class="note">Use sample details for this walkthrough. Nothing is sent or saved after you close the panel.</p><form id="delivery-form" autocomplete="off">${fields.map(([key,label,type,placeholder])=>`<label class="field">${label}<input name="${key}" type="${type}" required maxlength="160" placeholder="${placeholder}" value="${escapeHTML(order.delivery[key]||'')}"></label>`).join('')}<button class="primary">REVIEW PRINT →</button></form><button class="back" id="back">← Back to print selection</button>`;$('#delivery-form').onsubmit=e=>{e.preventDefault();order.delivery=Object.fromEntries(new FormData(e.target));order.step=2;renderOrder();};}
 if(order.step===2){const s=selected(),d=order.delivery;body.innerHTML=`<div class="print-preview"><img src="${w.small}" alt="${escapeHTML(w.title)}"><p>${escapeHTML(w.title)}<br>${s.sku}</p></div><dl class="summary"><div><dt>Print</dt><dd>${s.name} · Quantity ${order.quantity}</dd></div><div><dt>Image</dt><dd>${dimensions(s.width,s.height)}</dd></div><div><dt>Finished sheet</dt><dd>${dimensions(s.sheetWidth,s.sheetHeight)}</dd></div><div><dt>Print price</dt><dd>To be confirmed</dd></div><div><dt>Shipping & tax</dt><dd>To be confirmed</dd></div><div><dt>Total</dt><dd>Preview only — no charge</dd></div></dl><h3>Delivery</h3><p class="delivery-summary">${escapeHTML([d.name,d.email,d.address,`${d.city}, ${d.region} ${d.postal}`,d.country].join('\n'))}</p><button id="payment-next" class="primary">PREVIEW PAYMENT →</button><button class="back" id="back">← Edit delivery details</button>`;$('#payment-next').onclick=()=>{order.step=3;renderOrder();};}
 if(order.step===3){body.innerHTML=`<div class="mock-payment"><p class="eyebrow">PAYMENT DEMONSTRATION</p><h3>No payment will be taken.</h3><p class="note">Secure payment will be connected after print sizes and pricing are approved. This preview does not collect card information or place an order.</p></div><button class="primary" id="complete">COMPLETE PREVIEW →</button><button class="back" id="back">← Back to review</button>`;$('#complete').onclick=()=>{body.innerHTML=`<div class="print-preview"><img src="${w.small}" alt="${escapeHTML(w.title)}"></div><h3>Preview complete.</h3><p>You’ve reached the end of the print-order experience.</p><p class="note">No order was placed and no payment was processed.</p><button class="primary" id="return">RETURN TO THE GALLERY →</button>`;$('#return').onclick=closePanel;$('#return').focus();};}
 if($('#back'))$('#back').onclick=()=>{order.step--;renderOrder();};panel.scrollTop=0;if(panel.open){$('#panel-title').tabIndex=-1;$('#panel-title').focus();}
}
rest();updateInfo();
